### PR TITLE
separation of concerns

### PR DESCRIPTION
**Pull request by j0h**
more structuring. exceptions have their own namespace - well, this is mostly discussable.
some refactoring.

### CODE REVIEW

**Comment by j0h** [comment]
this resolves #1

**Comment by caveman-** [comment]
I would prefer to leave out comments like "wtf python?", also I am not sure about the main.py, what is the problem with keeping it within TicTacToe.py since executing TicTacToe.py would result in actually playing one game of TicTacToe and including it would only provide the functionality. We may also consider moving the PLAYER_ENTRY constant somewhere into the Tictactoe class

**Comment by j0h** [comment]
well, the "wtf python" comment is a left over. I am going to remove it in a second.

Considering the main.py this is needed to have some proper separation of concerns. Having communication and testing logic within the corresponding class is maybe not wanted and for sure not needed. I think the tictactoe class should provide a data model of the tictactoe game. maybe renaming the main.py into something more convenient would do the job?

I totally agree on your last point regarding the player_entry.

**Comment by caveman-** [comment]
I see the point having a dedicated file for the actual frontend of the program. Having said this, this code part is - by me - not considered actual frontend code but more of a gimmick to do very rough testing. Therefore I would keep it in Tictactoe.py or delete it entirely.

**Comment by j0h** [comment]
Ok, still it does not hurt to outsource that code. the tictactoe class gets a little more manageable and there is no code that does not relate to the modelling logic of the tictactoe class. Still then I see that my naming is inappropriate. How would it be to have some module called tests? Deleting it entirely is maybe not wanted. You still want to be able to test your changes.

**Comment by caveman-** [comment]
Sure it does not hurt, but I think since the tictactoe class is clear enough I still vote for keeping the code there over adding a new file (because adding a new file, which is that closely coupled to the tictactoe class appears odd to me). Although I can live with naming it appropriately (something like tictactoe_game.py or equally verbose).

**Comment by j0h** [comment]
You are right when you say that the test is only coupled to the tictactoe class. But his does not hold the other way around. The tictactoe class is totally independent of the really rough test, thus we would split the class away from the test as the test is not important to the class.

**Comment by caveman-** [comment]
I disagree there. Since this game is meant as "test code" (it is possible to argue on the sense of testing the class that way, but that's another story) I would keep it to the unit it tests. But as said: name it appropriately and it can be merged.

**Comment by caveman-** [comment]
Merged this by hand, thank you very much for the contribution!

**Pull request closed without merging**
